// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/db_models/exercise_db_model.dart';
import 'models/db_models/serie_db_model.dart';
import 'models/db_models/session_db_model.dart';
import 'models/db_models/user_db_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5862890105305746896),
    name: 'ExerciseDbModel',
    lastPropertyId: const obx_int.IdUid(11, 2333123488464876583),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7169298200443364002),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6767751380461083219),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 7512138164640766226),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6866241496277206355),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5543275967926317585),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8698252781473332000),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6637695151349133469),
        name: 'bpm',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8746461668711989197),
        name: 'useGlobalBpm',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2651881371397949630),
        name: 'useGlobalDuration',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4844644072889252871),
        name: 'sessionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 6320935432992693868),
        relationField: 'session',
        relationTarget: 'SessionDbModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7380477098368489075),
        name: 'serieId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 3643918276605505444),
        relationField: 'serie',
        relationTarget: 'SerieDbModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2333123488464876583),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1574390289755331795),
    name: 'SerieDbModel',
    lastPropertyId: const obx_int.IdUid(10, 8689450071786415520),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5534885171212211020),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3036369122989357474),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7717488119406773836),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1632880375448048184),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 5643094895915671589),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2979449737068388003),
        name: 'durationGlobal',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 32442264950764022),
        name: 'bpmGlobal',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3991715058979468626),
        name: 'durationValueGlobal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7270785168053605157),
        name: 'bpmValueGlobal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3134860534873742137),
        name: 'sessionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 7993516712805715477),
        relationField: 'session',
        relationTarget: 'SessionDbModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8689450071786415520),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 7246895725710162512),
        name: 'exercises',
        targetId: const obx_int.IdUid(1, 5862890105305746896),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1245805527222442569),
    name: 'SessionDbModel',
    lastPropertyId: const obx_int.IdUid(5, 6615348981232272076),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5709892317440313422),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4150527792579316023),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3565672966032942550),
        name: 'restDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4833078835820433624),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 5198730784708907338),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6615348981232272076),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 2934556526475261406),
        name: 'exercises',
        targetId: const obx_int.IdUid(1, 5862890105305746896),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 2263836851219020600),
        name: 'series',
        targetId: const obx_int.IdUid(2, 1574390289755331795),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5641128578864360602),
    name: 'UserDbModel',
    lastPropertyId: const obx_int.IdUid(2, 5857028345797195344),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2006424519839865079),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5857028345797195344),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5641128578864360602),
    lastIndexId: const obx_int.IdUid(6, 5198730784708907338),
    lastRelationId: const obx_int.IdUid(3, 2263836851219020600),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ExerciseDbModel: obx_int.EntityDefinition<ExerciseDbModel>(
      model: _entities[0],
      toOneRelations: (ExerciseDbModel object) => [
        object.session,
        object.serie,
      ],
      toManyRelations: (ExerciseDbModel object) => {},
      getId: (ExerciseDbModel object) => object.id,
      setId: (ExerciseDbModel object, int id) {
        object.id = id;
      },
      objectToFB: (ExerciseDbModel object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.duration);
        fbb.addInt64(5, object.bpm);
        fbb.addBool(6, object.useGlobalBpm);
        fbb.addBool(7, object.useGlobalDuration);
        fbb.addInt64(8, object.session.targetId);
        fbb.addInt64(9, object.serie.targetId);
        fbb.addInt64(10, object.lastUpdated.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final durationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final bpmParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final useGlobalBpmParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final useGlobalDurationParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object = ExerciseDbModel(
          name: nameParam,
          description: descriptionParam,
          duration: durationParam,
          bpm: bpmParam,
          uid: uidParam,
          useGlobalBpm: useGlobalBpmParam,
          useGlobalDuration: useGlobalDurationParam,
          lastUpdated: lastUpdatedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.session.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.session.attach(store);
        object.serie.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.serie.attach(store);
        return object;
      },
    ),
    SerieDbModel: obx_int.EntityDefinition<SerieDbModel>(
      model: _entities[1],
      toOneRelations: (SerieDbModel object) => [object.session],
      toManyRelations: (SerieDbModel object) => {
        obx_int.RelInfo<SerieDbModel>.toMany(1, object.id): object.exercises,
      },
      getId: (SerieDbModel object) => object.id,
      setId: (SerieDbModel object, int id) {
        object.id = id;
      },
      objectToFB: (SerieDbModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final uidOffset = fbb.writeString(object.uid);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, uidOffset);
        fbb.addBool(4, object.durationGlobal);
        fbb.addBool(5, object.bpmGlobal);
        fbb.addInt64(6, object.durationValueGlobal);
        fbb.addInt64(7, object.bpmValueGlobal);
        fbb.addInt64(8, object.session.targetId);
        fbb.addInt64(9, object.lastUpdated.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final durationGlobalParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final bpmGlobalParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final durationValueGlobalParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final bpmValueGlobalParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = SerieDbModel(
          name: nameParam,
          lastUpdated: lastUpdatedParam,
          durationGlobal: durationGlobalParam,
          bpmGlobal: bpmGlobalParam,
          durationValueGlobal: durationValueGlobalParam,
          bpmValueGlobal: bpmValueGlobalParam,
          description: descriptionParam,
          uid: uidParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.session.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.session.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<SerieDbModel>(
          object.exercises,
          store,
          obx_int.RelInfo<SerieDbModel>.toMany(1, object.id),
        );
        return object;
      },
    ),
    SessionDbModel: obx_int.EntityDefinition<SessionDbModel>(
      model: _entities[2],
      toOneRelations: (SessionDbModel object) => [],
      toManyRelations: (SessionDbModel object) => {
        obx_int.RelInfo<SessionDbModel>.toMany(2, object.id): object.exercises,
        obx_int.RelInfo<SessionDbModel>.toMany(3, object.id): object.series,
      },
      getId: (SessionDbModel object) => object.id,
      setId: (SessionDbModel object, int id) {
        object.id = id;
      },
      objectToFB: (SessionDbModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final uidOffset = fbb.writeString(object.uid);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.restDuration);
        fbb.addOffset(3, uidOffset);
        fbb.addInt64(4, object.lastUpdated.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final restDurationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = SessionDbModel(
          name: nameParam,
          restDuration: restDurationParam,
          uid: uidParam,
          lastUpdated: lastUpdatedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<SessionDbModel>(
          object.exercises,
          store,
          obx_int.RelInfo<SessionDbModel>.toMany(2, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<SessionDbModel>(
          object.series,
          store,
          obx_int.RelInfo<SessionDbModel>.toMany(3, object.id),
        );
        return object;
      },
    ),
    UserDbModel: obx_int.EntityDefinition<UserDbModel>(
      model: _entities[3],
      toOneRelations: (UserDbModel object) => [],
      toManyRelations: (UserDbModel object) => {},
      getId: (UserDbModel object) => object.id,
      setId: (UserDbModel object, int id) {
        object.id = id;
      },
      objectToFB: (UserDbModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = UserDbModel(name: nameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ExerciseDbModel] entity fields to define ObjectBox queries.
class ExerciseDbModel_ {
  /// See [ExerciseDbModel.id].
  static final id = obx.QueryIntegerProperty<ExerciseDbModel>(
    _entities[0].properties[0],
  );

  /// See [ExerciseDbModel.uid].
  static final uid = obx.QueryStringProperty<ExerciseDbModel>(
    _entities[0].properties[1],
  );

  /// See [ExerciseDbModel.name].
  static final name = obx.QueryStringProperty<ExerciseDbModel>(
    _entities[0].properties[2],
  );

  /// See [ExerciseDbModel.description].
  static final description = obx.QueryStringProperty<ExerciseDbModel>(
    _entities[0].properties[3],
  );

  /// See [ExerciseDbModel.duration].
  static final duration = obx.QueryIntegerProperty<ExerciseDbModel>(
    _entities[0].properties[4],
  );

  /// See [ExerciseDbModel.bpm].
  static final bpm = obx.QueryIntegerProperty<ExerciseDbModel>(
    _entities[0].properties[5],
  );

  /// See [ExerciseDbModel.useGlobalBpm].
  static final useGlobalBpm = obx.QueryBooleanProperty<ExerciseDbModel>(
    _entities[0].properties[6],
  );

  /// See [ExerciseDbModel.useGlobalDuration].
  static final useGlobalDuration = obx.QueryBooleanProperty<ExerciseDbModel>(
    _entities[0].properties[7],
  );

  /// See [ExerciseDbModel.session].
  static final session =
      obx.QueryRelationToOne<ExerciseDbModel, SessionDbModel>(
        _entities[0].properties[8],
      );

  /// See [ExerciseDbModel.serie].
  static final serie = obx.QueryRelationToOne<ExerciseDbModel, SerieDbModel>(
    _entities[0].properties[9],
  );

  /// See [ExerciseDbModel.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<ExerciseDbModel>(
    _entities[0].properties[10],
  );
}

/// [SerieDbModel] entity fields to define ObjectBox queries.
class SerieDbModel_ {
  /// See [SerieDbModel.id].
  static final id = obx.QueryIntegerProperty<SerieDbModel>(
    _entities[1].properties[0],
  );

  /// See [SerieDbModel.name].
  static final name = obx.QueryStringProperty<SerieDbModel>(
    _entities[1].properties[1],
  );

  /// See [SerieDbModel.description].
  static final description = obx.QueryStringProperty<SerieDbModel>(
    _entities[1].properties[2],
  );

  /// See [SerieDbModel.uid].
  static final uid = obx.QueryStringProperty<SerieDbModel>(
    _entities[1].properties[3],
  );

  /// See [SerieDbModel.durationGlobal].
  static final durationGlobal = obx.QueryBooleanProperty<SerieDbModel>(
    _entities[1].properties[4],
  );

  /// See [SerieDbModel.bpmGlobal].
  static final bpmGlobal = obx.QueryBooleanProperty<SerieDbModel>(
    _entities[1].properties[5],
  );

  /// See [SerieDbModel.durationValueGlobal].
  static final durationValueGlobal = obx.QueryIntegerProperty<SerieDbModel>(
    _entities[1].properties[6],
  );

  /// See [SerieDbModel.bpmValueGlobal].
  static final bpmValueGlobal = obx.QueryIntegerProperty<SerieDbModel>(
    _entities[1].properties[7],
  );

  /// See [SerieDbModel.session].
  static final session = obx.QueryRelationToOne<SerieDbModel, SessionDbModel>(
    _entities[1].properties[8],
  );

  /// See [SerieDbModel.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<SerieDbModel>(
    _entities[1].properties[9],
  );

  /// see [SerieDbModel.exercises]
  static final exercises =
      obx.QueryRelationToMany<SerieDbModel, ExerciseDbModel>(
        _entities[1].relations[0],
      );
}

/// [SessionDbModel] entity fields to define ObjectBox queries.
class SessionDbModel_ {
  /// See [SessionDbModel.id].
  static final id = obx.QueryIntegerProperty<SessionDbModel>(
    _entities[2].properties[0],
  );

  /// See [SessionDbModel.name].
  static final name = obx.QueryStringProperty<SessionDbModel>(
    _entities[2].properties[1],
  );

  /// See [SessionDbModel.restDuration].
  static final restDuration = obx.QueryIntegerProperty<SessionDbModel>(
    _entities[2].properties[2],
  );

  /// See [SessionDbModel.uid].
  static final uid = obx.QueryStringProperty<SessionDbModel>(
    _entities[2].properties[3],
  );

  /// See [SessionDbModel.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<SessionDbModel>(
    _entities[2].properties[4],
  );

  /// see [SessionDbModel.exercises]
  static final exercises =
      obx.QueryRelationToMany<SessionDbModel, ExerciseDbModel>(
        _entities[2].relations[0],
      );

  /// see [SessionDbModel.series]
  static final series = obx.QueryRelationToMany<SessionDbModel, SerieDbModel>(
    _entities[2].relations[1],
  );
}

/// [UserDbModel] entity fields to define ObjectBox queries.
class UserDbModel_ {
  /// See [UserDbModel.id].
  static final id = obx.QueryIntegerProperty<UserDbModel>(
    _entities[3].properties[0],
  );

  /// See [UserDbModel.name].
  static final name = obx.QueryStringProperty<UserDbModel>(
    _entities[3].properties[1],
  );
}
